name: Deploy my personal site

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install pnpm
          run: npm install -g pnpm

        - name: Setup NodeJs
          uses: actions/setup-node@v3
          with:
            node-version: 21
            cache: 'pnpm'

        - name: Install dependencies
          run: pnpm install --frozen-lockfile

        - name: Build Docker Image
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/yudya:latest .
        
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push Docker Image
          run: docker push ${{ secrets.DOCKER_USERNAME }}/yudya:latest

        - name: SSH into VPS and update code
          uses: appleboy/ssh-action@master
          with:
            port: ${{ secrets.SSH_PORT }}
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_DEPLOY_KEY }}
            script: |
                set -e

                if [ ! -d "/opt/app/yuyda" ]; then
                git clone git@github.com:Eugener3/yudya.git /opt/app/yuyda
                fi

                cd /opt/app/yuyda

                git fetch origin main
                git reset --hard origin/main

                echo "${{ secrets.ENV_CONTENTS }}" > /opt/app/yuyda/.env

                docker compose down

                docker compose pull

                docker system prune -af

                docker compose up -d --build

                docker ps -a
